config/routes.rb
Rails.application.routes.draw do

   root "searches#search"

  resources :searches, except: :all do
    collection do
      post :hotel_search
    end
  end
  get   'search' => 'searches#search'
  post 'query_search' => 'searches#query_search'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	has_many :products
end

app/models/room.rb
class Room < ActiveRecord::Base
  BASES   = [:single, :double, :triple, :quadruple, :quintuple, :sextuple]
  REGIMES = ['DES', 'EP', 'MAP', 'AI', 'PC']

  belongs_to    :tariff, dependent: :destroy
  accepts_nested_attributes_for :tariff, reject_if: :all_blank
end

app/models/search_handler.rb
class SearchHandler

	attr_accessor :hotels

	def self.call(search)
		self.send(search.data_type, search)
	end

	private
		
		def self.hotel_data(search)
			#Me conecto a la app
			#Armo el conjunto de productos
			#retorno los productos
			results = JSON.parse(File.read("test/fixtures/hotels.json"))
			results["hotels"].collect{|product_json| Product.new(product_json)}
		end

end

app/models/tariff.rb
class Tariff < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/searches_controller.rb
require "geography"
class SearchesController < ApplicationController
  before_action :set_search, only: [:query_search]

  def search
    @search      = Search.new
    @searchHotel = SearchHotel.new
    @searchHotel.rooms = 4.times.map { SearchRoom.new }
  end

  def hotel_search
    @searchHotel = SearchHotel.new(params[:search_hotel])
    @results = @searchHotel.call
    render 'search_result'
  end


  private
  
    def set_search
      @search = Search.new(search_params)
    end

    def search_params
      params.permit :destination_id, :date_in, :date_out, :nights, :childs, :minors, :adults
    end

    def hotel_search_params
      params.permit :destination_id, :date_in, :date_out
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def fa_link_to(text, url, options = {})
    icon = options.delete :icon
    text = content_tag(:i, '', :class => "fa fa-#{icon}") << " " << text  unless icon.blank?
    link_to text, url, options
  end	
end

app/views/application/_body.html.erb
  <div class="wrapper">
    
	  <%= render "layouts/application_header" %>
		
	  <%= render "layouts/application_sidebar" %>
    <!-- Right side column. Contains the navbar and content of the page -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->

      <aside class="principal">
        <%= yield(:content_header) %>

        <% flash.each do |name, msg| %>
          <div class="pad margin no-print">
            <%= content_tag :div, :class => "alert alert-#{ name == "error" ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
              <%= msg %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>

        
      </aside>
    </div><!-- ./wrapper -->
      
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>COTIZADOR</b> 2.0
      </div>
      <strong>Copyright &copy; 2015 <a href="">MI</a>.</strong> All rights reserved.
    </footer>
  </div><!-- ./wrapper -->

app/views/info/_generic_data.html.erb
Generico!!!!

app/views/info/_hotel_data.html.erb
<li>Nombre: <%=product.name%></li>
<li>In:<%=product.date_in%></li>
<li>Out:<%=product.date_out%></li>
<li>Prioridad:<%=product.priority%></li>
<li><%=product.data.stop_sale%></li>
<li>Estrellas:<%=product.data.stars%></li>
<li>Habitaciones:<%=product.data.rooms.size%></li>
<li>Precio:<%=product.data.rooms.first.value%></li>
<li>reg:<%=product.data.rooms.first.regime%></li>

app/views/layouts/_application_header.html.erb
     <header class="main-header">
        <!-- Logo -->

        <a href="" class="logo active"><i class="fa fa-sort-amount-desc fa-3"></i>  <b>Co</b>tizador</a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">Tenes 4 mensajes -</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <img src="/img/user2.png" class="img-circle" alt="User Image"/>
                          </div>
                          <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li><!-- end message -->
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="/img/user2.png" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="/img/user2.png" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="/img/user2.png" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Sales Department
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="/img/user2.png" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Reviewers
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">Espacio a rellenar.</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">Tenes 10 observaciones</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>

                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->
              <li class="dropdown tasks-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 9 tasks</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Create a nice theme
                            <small class="pull-right">40%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">40% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Some task I need to do
                            <small class="pull-right">60%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">60% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Make beautiful transitions
                            <small class="pull-right">80%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">80% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="/img/user2.png" class="user-image" alt="User Image"/>
                  
                  <span class="hidden-xs"> Aero La Plata</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="/img/user2.png" class="img-circle" alt="User Image" />
                    <p>
                     
                    </p>
                  </li>

                  <li class="user-footer">
          
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>

app/views/layouts/_application_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">

      <div class="pull-left info">
      <p>Esteban Fuhrmann</p>

        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <ul class="sidebar-menu">
      <li class="header">NAVEGACION</li>

      <li>
      <div class="box box-solid bg-teal-gradient collapsed-box">
         <div class="box-header">
           <i class="fa fa-th"></i>
           <h3 class="box-title">Ventas</h3>
           <div class="box-tools pull-right">
             <button class="btn bg-teal btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
             <button class="btn bg-teal btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
           </div>
         </div>
         <div class="box-body border-radius-none" style="display: none;">

           <div class="chart" id="line-chart" style="height: 250px;"></div>
             <div class="inner">
               <h3>53<sup style="font-size: 20px">%</sup></h3>
               <p>Bounce Rate</p>
             </div>
             <div class="icon">
               <i class="ion ion-stats-bars"></i>
             </div>
             <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
           </div>
           <div class="small-box bg-aqua">
             <div class="inner">
               <h3>150</h3>
               <p>New Orders</p>
             </div>
             <div class="icon">
               <i class="ion ion-bag"></i>
             </div>
             <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
           </div>
           <div class="small-box bg-green">
      

         </div><!-- /.box-body -->
      </div>         
         
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/_body.html.erb
  <div class="wrapper">
    
	  <%= render "layouts/application_header" %>
		
	  <%= render "layouts/application_sidebar" %>
    <!-- Right side column. Contains the navbar and content of the page -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->

      <aside class="principal">
        <%= yield(:content_header) %>

        <% flash.each do |name, msg| %>
          <div class="pad margin no-print">
            <%= content_tag :div, :class => "alert alert-#{ name == "error" ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
              <%= msg %>
            <% end %>
          </div>
        <% end %>
        <section class="content">
          <div class="row">

          <%= yield %>
          </div>
        </section >
        
      </aside>
    </div><!-- ./wrapper -->
      
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Aero</b> 
      </div>
      <strong>Copyright &copy; 2015 <a href="">MI</a>.</strong> All rights reserved.
    </footer>
  </div><!-- ./wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Aero Cotizador</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag "application"%>

  <%= csrf_meta_tags %>

</head>
  <body class="skin-black">

    <%= render "layouts/body" %>

    <%= javascript_include_tag 'application' %>

   <!-- Modal -->
   <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">Windows</h4>
         </div>
         <div class="modal-body">
             Para usar con ajax

             <div class="form-group">
            
             </div>  

         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
         </div>
         </form>
       </div>
     </div>
   </div>


  </body>
    <%= javascript_include_tag params[:controller] %> 

</html>

app/views/products/_product.html.erb
-----------------------------------------------------------------------------
<%= render "info/#{product.data_type.underscore}", product: product %><br>
-----------------------------------------------------------------------------

<br></br>

app/views/searches/_hotel.html.erb
<div class="table-responsive">
  <table class="table">

	<label>Cantidad
	<select id="quantityRoom">
		<option value=".room1" selected="selected">1 Habitación</option>
		<option value=".room1 , .room2">2 Habitaciones</option>
		<option value=".room1 , .room2, .room3">3 Habitaciones</option>
		<option value=".room1 , .room2, .room3 , .room4">4 Habitaciones</option>
	</select>

	<for>
	<br>
	   	<div id="" class="rooms" >
				<%number = 0%>
			   <%= f.simple_fields_for :rooms do |room|%>
			   		<div class="room<%=number = number + 1%>">
				   	  <label>Habitacion <%=number%></label><br> 
				      Adultos:<%= room.select :adult, (1..4), options = {}, html_options = {:class => "room#{number}"}%>
				      cat:<%= room.text_field :category,  html_options = {:class => "room#{number}"}%>
				      Menores:<%= room.select :minor, (1..4), options = {}, html_options = {:class => "room#{number}"}%>
				      Childs:<%= room.select  :child, (1..4), options = {}, html_options = {:class => "room#{number}"}%>
			      </div>
			     <br>
			   <%end%>
			</div>   
  </table>
</div>

app/views/searches/_search_hotel.erb
<div class="box box-primary">
<div class="box-header">
    <h3 class="box-title">Reserva simple hotel</h3>
</div><!-- /.box-header -->
  <!-- form start -->
  <%= simple_form_for @searchHotel, url: hotel_search_searches_path , :remote => true  do |f| %>
    <%= f.error_notification %>

      <div class="box-body">
          <div class="control-group">
          <%=f.label "Destino", :class => "control-label"%>
              <%#= f.select :destination_id, Destination.all.collect {|x| [x.name, x.id]}, {},  :class => "select2 select2_full" %>
          </div>

          <div class="form-group">
            <label>Fecha in:</label>
            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
            <%= f.text_field :date_in, :class => "form-control datemask"%>
            </div>
          </div>

          <div class="form-group">
            <label>Fecha out:</label>
            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= f.text_field :date_out, :class => "form-control datemask" %>
            </div>
          </div>
           
           <%= render  "searches/hotel" ,f: f %>

      </div><!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
        <%= f.button :submit %>

    </div>
  <% end %>

</div>

app/views/searches/search.html.erb
<div class="col-md-3">
              
  <!--Nav tabs-->
  <!--================================-->
  <ul class="nav nav-tabs nav-justified">
    <li class="active">
      <a href="#demo-asd-tab-1" data-toggle="tab" aria-expanded="true">
        <i class="fa fa-comments"></i>
        <span class="badge badge-purple">7</span>
      </a>
    </li>
    <li class="">
      <a href="#demo-asd-tab-2" data-toggle="tab" aria-expanded="false">
        <i class="fa fa-info-circle"></i>
      </a>
    </li>
    <li class="">
      <a href="#demo-asd-tab-3" data-toggle="tab" aria-expanded="false">
        <i class="fa fa-wrench"></i>
      </a>
    </li>
  </ul>
  <!--================================-->
  <!--End nav tabs-->



  <!-- Tabs Content -->
  <!--================================-->
  <div class="tab-content">

    <!--First tab (Contact list)-->
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <div class="tab-pane fade active in" id="demo-asd-tab-1">
          <%= render  "searches/search_hotel" %>
    </div>
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <!--End first tab (Contact list)-->


    <!--Second tab (Custom layout)-->
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <div class="tab-pane fade" id="demo-asd-tab-2">
        Dos
    </div>
    <!--End second tab (Custom layout)-->
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->


    <!--Third tab (Settings)-->
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <div class="tab-pane fade" id="demo-asd-tab-3">
      tres
    </div>
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <!--Third tab (Settings)-->

  </div>
</div>
<div class="col-md-9">
  <div id="results">
  </div>
</div>

app/views/searches/search_result.js.erb
$('#results').html('<%=j render(@results) %>');